### ISSUE TITLE
Any reason the URLs pin the version of devtools?

### ISSUE THREAD

**Issue by HugoDF** [KevinBatdorf/alpine-inline-devtools#2]
Since devtools probably shouldn't be used in production, we could use a wildcard pattern for them in the URLs eg.

`https://cdn.jsdelivr.net/gh/kevinbatdorf/alpine-inline-devtools@0.x.x/dist/index.js`

**Comment by KevinBatdorf** [comment]
It just wasnt updating fast enough. That one seems fine now but the one I was using before is still outdated

`https://cdn.jsdelivr.net/gh/kevinbatdorf/alpine-inline-devtools/dist/index.js`
